export const keywords = [
  // EVM, dApps, AI, General Services (first 100)
  'Ethereum',
  'Smart contracts',
  'Solidity',
  'Gas fees',
  'Layer 2',
  'Arbitrum',
  'Optimism',
  'Polygon',
  'zkEVM',
  'Rollups',
  'Ethers.js',
  'Viem',
  'MetaMask',
  'ERC20',
  'ERC721',
  'DeFi',
  'DAO',
  'ENS',
  'Tokenomics',
  'Mainnet',
  'Testnet',
  'Chainlink',
  'Oracles',
  'DEX',
  'Yield farming',
  'Web3 login',
  'WalletConnect',
  'NFT marketplace',
  'Voting protocol',
  'Governance',
  'Decentralized identity',
  'On-chain data',
  'Cross-chain',
  'Gasless transactions',
  'IPFS',
  'Token bridge',
  'Liquidity pool',
  'Staking',
  'Flash loans',
  'Smart wallet',
  'AI agent',
  'LLM',
  'Prompt engineering',
  'RAG',
  'Hugging Face',
  'OpenAI',
  'LangChain',
  'Fine-tuning',
  'Embeddings',
  'Vector database',
  'Chain-of-thought',
  'ReAct framework',
  'LLMOps',
  'Model inference',
  'Multimodal AI',
  'AutoGPT',
  'Agentic workflows',
  'AI orchestration',
  'Prompt chaining',
  'Memory context',
  'Therapy',
  'Counseling',
  'Mental health',
  'Cognitive behavioral therapy',
  'Couples therapy',
  'Online therapy',
  'Business consulting',
  'Financial planning',
  'Bookkeeping',
  'Tax filing',
  'Small business services',
  'Legal aid',
  'Incorporation',
  'HR services',
  'Career coaching',
  'Life coaching',
  'Personal training',
  'Nutritionist',
  'Education services',
  'Tutoring',
  'API',
  'SaaS',
  'Middleware',
  'Interoperability',
  'REST',
  'GraphQL',
  'Microservices',
  'Automation',
  'CRM',
  'No-code',
  'DevOps',
  'Cloud-native',
  'Edge computing',
  'Zero-knowledge proofs',
  'Privacy-preserving',
  'Digital identity',
  'Verification',
  'Credentialing',
  'Compliance',
  'Decentralized services',

  // General Professions and Services (additional 100)
  'Accounting',
  'Marketing',
  'Sales',
  'Copywriting',
  'Therapist',
  'Psychologist',
  'Virtual assistant',
  'Event planner',
  'Wedding planner',
  'Legal advisor',
  'Startup lawyer',
  'Freelancer management',
  'Remote hiring',
  'Payroll',
  'Time tracking',
  'Invoicing',
  'Budgeting',
  'Tax advisor',
  'Interior design',
  'Home cleaning',
  'Electrician',
  'Plumbing services',
  'Home renovation',
  'Pet care',
  'Dog walking',
  'Veterinary services',
  'Real estate agent',
  'Mortgage broker',
  'Home inspection',
  'Property management',
  'Fitness coach',
  'Yoga instructor',
  'Massage therapy',
  'Chiropractor',
  'Dermatologist',
  'Nutrition coach',
  'Meal planner',
  'Grocery delivery',
  'Childcare',
  'Babysitting',
  'Tutoring services',
  'Test prep',
  'Language learning',
  'Career services',
  'Resume writing',
  'Interview coaching',
  'College counseling',
  'Immigration services',
  'Translation',
  'Voiceover services',
  'Video editing',
  'Podcast editing',
  'Design services',
  'Logo design',
  'Branding',
  'UI/UX design',
  'Web design',
  'Social media management',
  'Content marketing',
  'SEO optimization',
  'Email marketing',
  'Market research',
  'Customer support',
  'Live chat support',
  'Helpdesk software',
  'E-commerce setup',
  'Product listing',
  'Inventory management',
  'Dropshipping',
  'Affiliate marketing',
  'Subscription billing',
  'Loyalty programs',
  'Appointment scheduling',
  'Telemedicine',
  'Online booking',
  'Fitness tracking',
  'Wellness coaching',
  'Mental health support',
  'Insurance advisor',
  'Financial advisor',
  'Stock trading',
  'Crypto investing',
  'Estate planning',
  'Notary services',
  'Document management',
  'Cloud storage',
  'File sharing',
  'Digital signing',
  'Workflow automation',
  'Form builder',
  'Survey tools',
  'Online classroom',
  'School administration',
  'Volunteer management',
  'Fundraising',
  'Nonprofit CRM',
  'Grant writing',
  'Donation tracking',
]
